"""add namespace

Revision ID: 4f9185093cd6
Revises: d359aeaffc57
Create Date: 2017-05-09 00:48:12.477444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9185093cd6'
down_revision = 'd359aeaffc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespace',
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['group.name'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namespace')
    # ### end Alembic commands ###
