"""empty message

Revision ID: d359aeaffc57
Revises: f773309b2ee4
Create Date: 2017-05-09 00:21:41.471498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd359aeaffc57'
down_revision = 'f773309b2ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
